apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd-ns
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  project: default
  source:
    repoURL: https://github.com/aaboelala/observability_proj.git
    targetRevision: HEAD
    path: argocd/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  