apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  project: default
  source:
    repoURL: https://github.com/aaboelala/observability_proj.git
    targetRevision: HEAD
    path: manifests/service-my-app.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  